name: Build-Test

on:
  push:
    branches: [ Assignment* ]
  pull_request:
    branches: [ Assignment* ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./SecretSanta/
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
      
    - name: Npm Build
      working-directory: ./SecretSanta/src/SecretSanta.Web/
      run: |
        npm install
        npm run build:prod
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    #for some reason it's not running all tests when executing on the sln
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal

    - name: Test Api
      working-directory: ./SecretSanta/test/SecretSanta.Api.Tests/
      run: dotnet test --no-build --verbosity normal

    - name: Test Web
      working-directory: ./SecretSanta/test/SecretSanta.Web.Tests/
      run: dotnet test --no-build --verbosity normal
